language: node_js
node_js:
  - '10'
# Travis-CI Caching
cache:
  yarn:true
  directories:
    - node_modules
install:
  - npm run bootstrap
# 只检测 master 分支的 push
branches:
  only:
    - master
script:
  - npm run test
  - npm run build
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
deploy:
  provider: script
  script: 'npm run publish'
  on:
    tags: true
after_deploy:
  - npm run build:doc
  - npm run deploy    
