language: node_js
node_js:
  - '10'
# Travis-CI Caching
cache:
  directories:
    - node_modules
install: yarn
# 只检测 master 分支的 push
branches:
  only:
    - master
script:
  - npm run test
before_deploy:
  - npm run build
  - npm run build:doc
  - npm run deploy
deploy:
  provider: script
  script: 'npm run publish'
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  skip_cleanup: true
  on:
    tags: true
